name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'    # ensures `git submodule update --init` runs

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential meson cmake make gcc \
            pkg-config clang ninja-build \
            rustc cargo \
            libx11-dev libx11-xcb-dev libxext-dev libxres-dev \
            libxcb1-dev libxcb-composite0-dev libxcb-xfixes0-dev \
            libxcb-randr0-dev libxcb-shape0-dev libxcb-util-dev \
            libxrender-dev libxtst-dev libxdamage-dev libxcomposite-dev \
            libxcursor-dev libxxf86vm-dev libxmu-dev \
            libxkbcommon-dev \
            libwayland-client0 libwayland-dev wayland-protocols \
            libwayland-egl1-mesa libwayland-bin \
            libvulkan-dev vulkan-utility-libraries-dev \
            libdrm-dev libgbm-dev libegl1-mesa-dev libgles2-mesa-dev \
            libpipewire-0.3-dev \
            libpixman-1-dev libudev-dev \
            libseat1 libseat-dev \
            libinput-dev \
            libxcb-ewmh-dev libxcb-icccm4-dev libxcb-res0-dev \
            xserver-xorg-dev xorg-dev \
            libsystemd-dev \
            libdisplay-info-bin libeis1 \
            libdecor-0-dev \
            glslang-dev glslang-tools \
            libcap-dev

      - name: Build Gamescope
        run: |
          ls
          pwd
          cd deps/gamescope
          ls
          pwd
          meson setup build/
          ninja -C build/
