name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'    # ensures `git submodule update --init` runs

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build

      - name: Gamescope
        run: |
          ls
          pwd
          cd deps/gamescope
          ls
          pwd
          meson setup build/
          ninja -C build/
